kafka:
  host: "kafka1:9093"
  topic: "nginx-log"
  groupId: "1"
  numPartitions: 3
  replication: -1 
es:
  host: http://es:9200
  preName: logstash-

chunzhen:
  path: config/qqwry.dat
ip2location:
  path: config/IP2LOCATION-LITE-DB11.BIN